[project]
name = "phonchar"
version = "0.1.0"
description = "Fast per character phoneme classification (G2P)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
]

[dependency-groups]
dev = ["pytest>=8.4.2"]

[tool.pytest.ini_options]
pythonpath = [
  "."
]
